[project]
name = "tax-engineer-homework"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.11.5",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "ipykernel>=6.29.5",
]
test = [
    "pytest>=8.4.0",
]
